// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCz-2VXfq7_L_tNxi4LURbzPQFVkZ5KU',
    appId: '1:889971971864:web:b48b1b0cc3e4c07a55f06d',
    messagingSenderId: '889971971864',
    projectId: 'flutterchatapp-608ad',
    authDomain: 'flutterchatapp-608ad.firebaseapp.com',
    storageBucket: 'flutterchatapp-608ad.appspot.com',
    measurementId: 'G-YSGZZ29RH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXNRlN7aRbgiDANylzaoDIo17GbfBrxKc',
    appId: '1:889971971864:android:c4f9d657e8de92e755f06d',
    messagingSenderId: '889971971864',
    projectId: 'flutterchatapp-608ad',
    storageBucket: 'flutterchatapp-608ad.appspot.com',
  );
}
